# 启动云原生开发环境的配置（控制开发环境如何启动）
$:
  vscode:
    - docker:
        # 指定开发环境启动时的基础镜像
        image: docker.cnb.cool/iiistudio/os/docker/python:3.12.11
      services:
        - vscode  # 启用 VSCode 远程开发服务
        - docker  # 启用 dind 服务（用于构建镜像等操作）

# 构建并推送镜像的任务（原有的 push 配置保留）
main:
  push:
    - services:
        - docker
      imports:
        - https://cnb.cool/IIIStudio/key/-/blob/main/github/env.yml
      stages:
        - name: 同步到GitHub
          image: tencentcom/git-sync 
          settings:
            target_url: https://github.com/IIIStudio/PasteNote.git
            auth_type: https
            git_user: ${GIT_USERNAME}
            git_email: ${GIT_EMAIL} 
            username: ${GIT_USERNAME} 
            password: ${GIT_ACCESS_TOKEN}
            branch: main
            sync_mode: mirror  # 镜像模式，直接覆盖
            force: true
    - services:
        - docker
      imports:
        - https://cnb.cool/IIIStudio/key/-/blob/main/cos/cnb.yml
      stages:
        - name: 上传COS
          image: tencentcom/coscli
          script: |
            echo "当前仓库名称: $CNB_REPO_NAME"
            coscli config set --secret_id $COS_SECRET_ID --secret_key $COS_SECRET_KEY
            coscli config add --init-skip=true -b $COS_BUCKET -r $COS_REGION
            coscli cp ./PasteNote cos://$COS_BUCKET/$CNB_REPO_NAME  -r
    - services:
        - docker
      stages:
        - name: 获取版本号
          script: |
            VERSION=$(grep '"version"' PasteNote/manifest.json | cut -d'"' -f4)
            echo "v$VERSION"
          exports:
            info: FILE_NAME
        - name: 创建新标签
          type: git:release
          options:
            overlying: true
            latest: true
            tag: ${FILE_NAME}
        - name: 压缩文件
          timeout: 7200s
          script: apt-get update && apt-get install -y zip && cd /workspace/PasteNote && zip -r ../PasteNote.zip *
        - name: 上传附件
          image: cnbcool/attachments:latest
          settings:
            tag: ${FILE_NAME}
            attachments:
              - "PasteNote.zip"